version: '3.6'
services:
  # db:
  #   image: postgres
  #   restart: always
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_PASSWORD: 123
  #     POSTGRES_DB: sophia

  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
    # volumes:
    #   - cache:/data
#  back:
#    build: ./
#    ports:
#      - '8080:8080'
#    volumes:
#      - ./src:/app/src
#    depends_on:
#      - db

# volumes:
#   postgres-data:
#     external: true
#     name: postgres-data
#   cache:
